version: "2"

services:
  telegrambot:
    build: .
    environment:
      TOKEN: $TOKEN
      WEBHOOK_URL: $WEBHOOK_URL
      NOPINGDAYS: $NOPINGDAYS
      NAMES: $NAMES
      HOUR: $HOUR
      MINUTE: $MINUTE
    volumes:
      - ./names.yml:/names/names:Z

