apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  name: telegrambot
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.io/surajd/telegrambot
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
